/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class invoker_sgx_invoker */

#ifndef _Included_invoker_sgx_invoker
#define _Included_invoker_sgx_invoker
#ifdef __cplusplus
extern "C" {
#endif
#undef invoker_sgx_invoker_N
#define invoker_sgx_invoker_N 30L
#undef invoker_sgx_invoker_cacheSize
#define invoker_sgx_invoker_cacheSize 100L
#undef invoker_sgx_invoker_expire
#define invoker_sgx_invoker_expire 1000LL
/*
 * Class:     invoker_sgx_invoker
 * Method:    print_ms
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_invoker_sgx_1invoker_print_1ms
  (JNIEnv *, jclass);

/*
 * Class:     invoker_sgx_invoker
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_invoker_sgx_1invoker_init
  (JNIEnv *, jclass);

/*
 * Class:     invoker_sgx_invoker
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_invoker_sgx_1invoker_destroy
  (JNIEnv *, jclass);

/*
 * Class:     invoker_sgx_invoker
 * Method:    commit
 * Signature: (J[II[DI[FI[JI[CI[BI)I
 */
JNIEXPORT jint JNICALL Java_invoker_sgx_1invoker_commit
  (JNIEnv *, jclass, jlong, jintArray, jint, jdoubleArray, jint, jfloatArray, jint, jlongArray, jint, jcharArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
